#! /bin/bash

ln -sv $DOTFILES/nvimrc ~/.config/nvim/init.vim
ln -sv $DOTFILES/ideavimrc ~/.ideavimrc
ln -sv $DOTFILES/zshrc ~/.config/zsh/.zshrc
ln -sv $DOTFILES/zprofile ~/.zprofile
ln -sv $DOTFILES/install ~/.scripts/ins
ln -sv $DOTFILES/update ~/.scripts/upd
cp -i $DOTFILES/karabiner.json ~/.config/karabiner/karabiner.json
